#! /bin/sh

search_paths=$@

case "$search_paths" in
    '') search_paths=..;; # XXX Assuming we're located somewhere with other repos
esac

DATA_DIR=data

prefix="$DATA_DIR"/repos."$(hostname)"."$(date +'%Y-%m-%d--%H:%M:%S%z')"
data_file="$prefix".rktd
graph_file="$prefix".dot
image_file="$prefix".png

mkdir -p "$DATA_DIR"

./git-locate --search $search_paths | ./git-locate --read --graph --multi-homed -o "$graph_file" && \
neato -Tpng -Goverlap=false -o "$image_file" "$graph_file" && \
sxiv "$image_file"
